---
# Control file for Travis CI.
# Must be located in the root directory of the Git repository.

notifications:
  email: false

os:
  - linux

language: python
python:
  - "2.7"

before_install:
  - sudo make install_apt_deps

install:
  - make build_dir
  - sudo pip list

script:
  - make build

after_success:
  - bash publish-gh-pages.sh
