# -*- mode: ruby -*-
# vi: set ft=ruby :

# =========================================================================
# The servers in our environment
# =========================================================================
servers=[
    {
      :hostname => "reno",
      :box => "geerlingguy/ubuntu1604",
      :ip => "192.168.159.11",
      :port => 50716,
      :ram => 1024,
      :cpu => 1
    },
]


# =========================================================================
# Provisioning
# =========================================================================
$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
mkdir -p /applications
cp -r /vagrant/example-app/* /applications/
apt-get update -y
apt-get install -y python-pip
pip install -U pip
pip install -U setuptools
pip install -r /applications/tsk_mgr/requirements.txt
pip install -r /applications/tsk_mgr/doc-requirements.txt
pip install tox
SCRIPT


Vagrant.configure(2) do |config|

  # =========================================================================
  # The general settings
  # =========================================================================
  config.vm.provider "virtualbox" do |v|
    # https://www.vagrantup.com/docs/virtualbox/configuration.html#linked-clones
    v.linked_clone = true
  end

  # =========================================================================
  # Server specific settings
  # =========================================================================
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:port], id: "ssh"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
      end

      node.vm.provision "shell", inline: $script
    end
  end
end