# -*- mode: ruby -*-
# vi: set ft=ruby :

servers=[
    {
      :box => "geerlingguy/ubuntu1604",
      :hostname => "golang",
      :ip => "192.168.27.11",
      :port => 52287,
      :ram => 4096,
      :cpu => 4
    },
]

Vagrant.configure("2") do |config|

    servers.each do |machine|

        config.vm.define machine[:hostname] do |node|

            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:port], id: "ssh"

            node.vm.provider "virtualbox" do |vb|
                vb.memory = machine[:ram]
                vb.cpus = machine[:cpu]
            end

            if machine == servers.last

                node.vm.provision "ansible" do |ansible|
                    ansible.limit = "all"
                    ansible.playbook = "provisioning_playbook.yml"
                end

            end

        end

    end

end

