---
# tasks file for roles/workload-deploy

- name: "Copy the applications to the servers."
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
  with_items:
    - eat_cpu.py
    - eat_disk.py
    - eat_memory.py
