---
# tasks file for grafana

- name: "Install from operating system package."
  include: apt_install.yml
  when: install_method == "os-package"

- name: "Install from source."
  include: source_install.yml
  when: install_method == "source"
