# -*- mode: ruby -*-
# vi: set ft=ruby :

# =========================================================================
# The servers in our environment
# =========================================================================
servers=[
    {
      :hostname => "es1",
      :box => "geerlingguy/ubuntu1604",
      :ip => "192.168.78.11",
      :port => 50211,
      :ram => 3072,
      :cpu => 1
    },
    {
      :hostname => "app1",
      :box => "geerlingguy/ubuntu1604",
      :ip => "192.168.78.12",
      :port => 50212,
      :ram => 1024,
      :cpu => 1
    },
    {
      :hostname => "app2",
      :box => "geerlingguy/ubuntu1604",
      :ip => "192.168.78.13",
      :port => 50213,
      :ram => 1024,
      :cpu => 1
    },
]


Vagrant.configure(2) do |config|

  # =========================================================================
  # The general settings
  # =========================================================================
  config.vm.provider "virtualbox" do |v|
    # https://www.vagrantup.com/docs/virtualbox/configuration.html#linked-clones
    v.linked_clone = true
  end

  # =========================================================================
  # Server specific settings
  # =========================================================================
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:port], id: "ssh"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
      end

    end
  end
end