---

# ===========================================================================
# Do basic setup on all hosts
# ===========================================================================
- hosts: all
  become: true
  gather_facts: false

  vars:
    user_name: elastic
    user_password: elastic
    user_group: elastic

  tasks:
    - name: "Wait for SSH to be ready."
      become: false
      delegate_to: localhost
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: "OpenSSH"
        delay: 1
        timeout: 300

    - name: "Add our servers to the hosts file."
      lineinfile:
        dest: /etc/hosts
        # use the IP address we specified in the Vagrantfile
        line: '{{ hostvars[item].ansible_host }} {{item}}'
      with_items: '{{ groups["all"] }}'

    - name: "Ping each other via DNS names."
      ping:
      with_items: '{{ groups["all"] }}'

    - name: "Ensure system package cache is updated."
      apt:
        update_cache: "yes"
        cache_valid_time: 3600

    - name: "Create a group for Elasticsearch."
      group:
        name: "{{ user_group }}"
        state: present

    - name: "Creating user for Elasticsearch group."
      user:
        name: "{{ user_name }}"
        password:  "{{ user_password | password_hash('sha512') }}"
        group: "{{ user_group }}"
        system: true
        state: present

    - name: "Install JAVA runtime."
      apt:
        package: openjdk-8-jre-headless

    - name: "Download file with checksum check."
      get_url:
        url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.1.tar.gz
        dest: /home/elastic/
        checksum: sha512:dcc23ef80ad2545490508d3e9db2fd0e6ae9a99cece0990f537c522265961dad234734548d1d86288af7f65a6ee681f5624d2c0e71df0e1dcc32fdb56dcefe92
        owner: "{{ user_name }}"
        group: "{{ user_group }}"

    - name: "Unarchive the elasticsearch archive."
      unarchive:
        src: /home/elastic/elasticsearch-6.1.1.tar.gz
        dest: /home/elastic/
        remote_src: yes
        owner: "{{ user_name }}"
        group: "{{ user_group }}"

    - name: "Run elasticsearch as daemon."
      command: "sudo -u {{ user_name }} ./bin/elasticsearch -d -p pid"
      args:
        chdir: /home/elastic/elasticsearch-6.1.1/
      async: 10
      poll: 0

    - name: "Check if Elasticsearch is up an running."
      uri:
        url: http://127.0.0.1:9200
        method: GET
      register: reg_get_api
      until: reg_get_api.status == 200
      retries: 5
