# The full config is at:
#   https://prometheus.io/docs/operating/configuration/

global:
  # How frequently to scrape targets by default.
  scrape_interval: 15s

scrape_configs:

  - job_name: 'monitoring'
    target_groups:
      - targets: ['localhost:9100']
        labels:
          name: 'monitoring'
          owner: 'mzio'

  - job_name: 'app-server-1'
    target_groups:
      - targets: ['app-server-1:9100']
        labels:
          name: 'app-server-1'
          arch: 'x86'

  - job_name: 'app-server-2'
    target_groups:
      - targets: ['app-server-2:9100']
        labels:
          name: 'app-server-2'
          arch: 'x86'
