---
# tasks file for roles/ssh-accessible

- name: "Wait for SSH to be ready."
  become: false
  delegate_to: localhost
  wait_for:
    port: 22
    host: '{{ ansible_host }}'
    search_regex: "OpenSSH"
    delay: 5
    timeout: 300
