# -*- mode: ruby -*-
# vi: set ft=ruby :

# =========================================================================
# The servers in our environment
# =========================================================================
servers=[
    {
      :hostname => "ls1",
      :box => "geerlingguy/ubuntu1604",
      :ip => "192.168.73.12",
      :port => 50232,
      :ram => 4096,
      :cpu => 4
    },
]


Vagrant.configure(2) do |config|

  # =========================================================================
  # The general settings
  # =========================================================================
  config.vm.provider "virtualbox" do |v|
    # https://www.vagrantup.com/docs/virtualbox/configuration.html#linked-clones
    v.linked_clone = true
  end

  # =========================================================================
  # Server specific settings
  # =========================================================================
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:port], id: "ssh"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
      end

      if machine == servers.last
        node.vm.provision "ansible" do |ansible|
          ansible.limit = "all"
          ansible.playbook = "provisioning_playbook.yml"
        end
      end

    end
  end
end